2016-08-30 15:28:21,575 - tornado.application - ERROR - Uncaught exception GET / (127.0.0.1)
HTTPServerRequest(protocol='http', host='127.0.0.1:8081', method='GET', uri='/', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Accept-Language': 'zh-CN,zh;q=0.8', 'Accept-Encoding': 'gzip, deflate, sdch', 'Host': '127.0.0.1:8081', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36', 'Connection': 'keep-alive', 'Cookie': '_xsrf=9dd8cba361c449a9a63bf55f16490717; check_code=55Oc54af6JKC6JC9|1472540030|23eabcc282654786af10c7d7208bf3685c350ff5', 'Cache-Control': 'max-age=0', 'Upgrade-Insecure-Requests': '1'}) - [web.py:1548]
Traceback (most recent call last):
  File "F:\program\python27\lib\site-packages\tornado\web.py", line 1446, in _execute
    result = self.prepare()
  File "G:\myProgram\python\myExecise\tornado_blog\Controller\BaseHandler.py", line 15, in prepare
    if self.request.headers["Content-Type"].startswith("application/json"):
  File "F:\program\python27\lib\site-packages\tornado\httputil.py", line 215, in __getitem__
    return self._dict[_normalized_headers[name]]
KeyError: 'Content-Type'
2016-08-30 15:28:24,440 - tornado.application - ERROR - Uncaught exception GET / (127.0.0.1)
HTTPServerRequest(protocol='http', host='127.0.0.1:8081', method='GET', uri='/', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Accept-Language': 'zh-CN,zh;q=0.8', 'Accept-Encoding': 'gzip, deflate, sdch', 'Host': '127.0.0.1:8081', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36', 'Connection': 'keep-alive', 'Cookie': '_xsrf=9dd8cba361c449a9a63bf55f16490717; check_code=55Oc54af6JKC6JC9|1472540030|23eabcc282654786af10c7d7208bf3685c350ff5', 'Cache-Control': 'max-age=0', 'Upgrade-Insecure-Requests': '1'}) - [web.py:1548]
Traceback (most recent call last):
  File "F:\program\python27\lib\site-packages\tornado\web.py", line 1446, in _execute
    result = self.prepare()
  File "G:\myProgram\python\myExecise\tornado_blog\Controller\BaseHandler.py", line 15, in prepare
    if self.request.headers["Content-Type"].startswith("application/json"):
  File "F:\program\python27\lib\site-packages\tornado\httputil.py", line 215, in __getitem__
    return self._dict[_normalized_headers[name]]
KeyError: 'Content-Type'
2016-08-30 18:11:09,265 - tornado.application - ERROR - Uncaught exception GET /v01/check_code?1472551869242 (127.0.0.1)
HTTPServerRequest(protocol='http', host='127.0.0.1:8081', method='GET', uri='/v01/check_code?1472551869242', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Accept-Language': 'zh-CN,zh;q=0.8', 'Accept-Encoding': 'gzip, deflate, sdch', 'Host': '127.0.0.1:8081', 'Accept': 'image/webp,image/*,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36', 'Connection': 'keep-alive', 'Referer': 'http://127.0.0.1:8081/v01/signout', 'Cookie': '_xsrf=9dd8cba361c449a9a63bf55f16490717; check_code="2|1:0|10:1472551844|10:check_code|16:5qiq55Sf5p6d6IqC|5712e3248fc27efa871a3f09bdc7f4b80d31a7a53637c149d970edcdfcdf0527"'}) - [web.py:1548]
Traceback (most recent call last):
  File "F:\program\python27\lib\site-packages\tornado\web.py", line 1467, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "G:\myProgram\python\myExecise\tornado_blog\Controller\CheckcodeHandler.py", line 16, in get
    code_img, capacha_code = image.randChinese()
  File "G:\myProgram\python\myExecise\tornado_blog\utils\check_code.py", line 72, in randChinese
    chengyu = RandomChar().GB2312()
  File "G:\myProgram\python\myExecise\tornado_blog\utils\check_code.py", line 29, in GB2312
    chengyu = RandomChar.chengyu[num]
KeyError: 100
